"""empty message

Revision ID: 9eab4d4e986c
Revises: 3ae9ea1f2607
Create Date: 2019-10-28 21:38:52.404247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eab4d4e986c'
down_revision = '3ae9ea1f2607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bilibili', sa.Column('href', sa.String(length=140), nullable=True))
    op.add_column('bilibili', sa.Column('src', sa.String(length=140), nullable=True))
    op.drop_column('bilibili', 'pic')
    op.drop_column('bilibili', 'aid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bilibili', sa.Column('aid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('bilibili', sa.Column('pic', mysql.VARCHAR(length=140), nullable=True))
    op.drop_column('bilibili', 'src')
    op.drop_column('bilibili', 'href')
    # ### end Alembic commands ###
