"""empty message

Revision ID: bf3b526df736
Revises: 54c5e3f77877
Create Date: 2019-10-27 16:32:16.882966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3b526df736'
down_revision = '54c5e3f77877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanjiang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookname', sa.String(length=140), nullable=True),
    sa.Column('href', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sanjiang')
    # ### end Alembic commands ###
